// src/pages/projects.tsx
import React from "react"
import { ExternalLink } from "../components/Link"
import { UnorderedList } from "../components/UnorderedList"
import { ListItem } from "../components/ListItem"
import { Helmet } from "react-helmet"

const projects = [
  {
    name: "Personal website",
    tags: [
      "Gatsby",
      "Preact",
      "Netlify",
      "Static site generator",
      "Styled components",
    ],
  },
  {
    name: "Corporate projects",
    tags: [
      "React",
      "Next",
      "Redux",
      "Apollo GraphQL",
      "Server-side rendering",
      "Material-UI",
      "CSS in JS",
      "Webpack",
      "Express",
      "Docker",
      "Kubernetes",
      "Azure DevOps",
    ],
  },
  {
    name: "Depoclaim",
    link: "https://depoclaim.com",
    tags: [
      "Vue.js",
      "Nuxt",
      "Netlify",
      "Static site generator",
      "Contentful",
      "Bootstrap 4",
      "Markdown",
    ],
  },
  {
    name: "Mátyás Bittenbinder",
    link: "https://mbittenbinder.com",
    tags: [
      "Vue.js",
      "Nuxt",
      "Netlify",
      "Static site generator",
      "Contentful",
      "Bootstrap 4",
    ],
  },
  {
    name: "Jolien Wesselink",
    link: "https://jolienwesselink.nl",
    tags: [
      "Vue.js",
      "Nuxt",
      "Netlify",
      "Static site generator",
      "Contentful",
      "Bootstrap 4",
      "Markdown",
    ],
  },
]

const allTags: string[] = projects.reduce(
  (accumulator, { tags }) => [...accumulator, ...tags],
  [] as string[]
)
const uniqueTags = Array.from(new Set(allTags))

const ProjectPage = () => (
  <>
    <Helmet>
      <title>Projects</title>
      <meta content={uniqueTags.join(", ")} name="keywords" />
    </Helmet>

    <main>
      <h2>Projects</h2>
      <UnorderedList>
        {projects.map(({ name, link = null, tags }) => (
          <ListItem key={name}>
            {link ? (
              <h3>
                <ExternalLink href={link}>{name}</ExternalLink>
              </h3>
            ) : (
              <h3>{name}</h3>
            )}
            <UnorderedList>
              {tags.map(tag => (
                <ListItem inline key={tag}>
                  {tag}
                </ListItem>
              ))}
            </UnorderedList>
          </ListItem>
        ))}
      </UnorderedList>
    </main>
  </>
)

export default ProjectPage

// pages/projects/index.vue
<template>
  <main>
    <h2>Projects</h2>
    <i-unordered-list :items="prodProjects" item-key="name">
      <template slot-scope="{ item: { name, link = null, tags } }">
        <h3 v-if="link" ><i-link :to="link" external>{{ name }}</i-link></h3>
        <h3 v-else>{{ name }}</h3>
        <i-unordered-list :items="tags" inline>
          <template slot-scope="{ item }">
            {{ item }}
          </template>
        </i-unordered-list>
      </template>
    </i-unordered-list>
  </main>
</template>

<script>
import IUnorderedList from '~/components/IUnorderedList'
import IListItem from '~/components/IListItem'
import ILink from '~/components/ILink'

export default {
  components: {
    IUnorderedList,
    IListItem,
    ILink
  },
  head: () => ({
    title: 'Projects'
  }),
  created() {
    // set non reactive static data
    // https://github.com/vuejs/vue/issues/6004
    this.prodProjects = [
      {
        name: 'Personal website',
        tags: ['Vue.js', 'Nuxt', 'Netlify', 'SSG', 'PostCSS']
      },
      {
        name: 'Depoclaim',
        link: 'https://depoclaim.com',
        tags: ['Vue.js', 'Nuxt', 'Netlify', 'SSG', 'Contentful', 'Bootstrap 4', 'Markdown']
      },
      {
        name: 'Mátyás Bittenbinder',
        link: 'https://mbittenbinder.com',
        tags: ['Vue.js', 'Nuxt', 'Netlify', 'SSG', 'Contentful', 'Bootstrap 4']
      },
      {
        name: 'Jolien Wesselink',
        link: 'https://jolienwesselink.nl',
        tags: ['Vue.js', 'Nuxt', 'Netlify', 'SSG', 'Contentful', 'Bootstrap 4', 'Markdown']
      }
    ]
  }
}
</script>
